services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    volumes:
      - /home/mark1/Videos/guacamole:/record:rw
    restart: always
    networks:
      guacnet:

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./conf/mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    depends_on:
      - guacd
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=guacamole_password
    restart: always
    networks:
      guacnet:

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - mysql
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build:/etc/nginx/build 
    ports:
      - "80:80"
    restart: always
    networks:
      guacnet:
        ipv4_address: 10.5.0.4

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    depends_on:
      - nginx
    links:
      - guacd
      - mysql
      - nginx
    volumes:
      - ./conf/guacamole/server.xml:/usr/local/tomcat/conf/server.xml
      - ./conf/guacamole:/root/.custom_guacamole
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=mysql
      - NGINX_HOSTNAME=nginx
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=guacamole_password
      - GUACAMOLE_HOME=/root/.custom_guacamole
    restart: always
    networks:
      guacnet:
        ipv4_address: 10.5.0.5

networks:
  guacnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
